server {
  listen 8080;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location = /assets/runtime-config.js {
    add_header Cache-Control "no-store";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  error_page 500 502 503 504 /50x.html;
}
